import React, { useEffect, useState } from "react";
import CountriesDropdown from "./CountriesDropdown.js";

const mockedData = [
    {name:"SOUTH AFRICA"},
    {name:"UNITED KINGDOM"},
    {name:"ARGENTINA"},
    {name:"AUSTRALIA"},
    {name:"BAHAMAS"},
    {name:"BELGIUM"},
    {name:"BRAZIL"},
    {name:"CANADA"},
    {name:"CHINA"},
    {name:"COLOMBIA"},
    {name:"CUBA"},
    {name:"DOMINICAN REPUBLIC"},
    {name:"ECUADOR"},
    {name:"EL SALVADOR"},
    {name:"FRANCE"},
    {name:"GERMANY"},
    {name:"GUATEMALA"},
    {name:"HAITI"},
    {name:"HONDURAS"},
    {name:"INDIA"},
    {name:"IRELAND"},
    {name:"ISRAEL"},
    {name:"ITALY"},
    {name:"JAPAN"},
    {name:"KOREA"},
    {name:"MEXICO"},
    {name:"NETHERLANDS"},
    {name:"PHILIPPINES"},
    {name:"SPAIN"},
    {name:"SWEDEN"},
    {name:"SWITZERLAND"},
    {name:"TAIWAN"},
    {name:"VENEZUELA"},
    {name:"VIET NAM"},
    {name:"AFGHANISTAN"},
    {name:"ALBANIA"},
    {name:"ALGERIA"},
    {name:"AMERICAN SAMOA"},
    {name:"ANDORRA"},
    {name:"ANGOLA"},
    {name:"ARMENIA"},
    {name:"AUSTRIA"},
    {name:"AZERBAIJAN"},
    {name:"BAHRAIN"},
    {name:"BANGLADESH"},
    {name:"BARBADOS"},
    {name:"BELARUS"},
    {name:"BELIZE"},
    {name:"BENIN"},
    {name:"BERMUDA"},
    {name:"BHUTAN"},
    {name:"BOLIVIA"},
    {name:"BOSNIA AND HERZEGOVINA"},
    {name:"BOTSWANA"},
    {name:"BULGARIA"},
    {name:"BURKINA FASO"},
    {name:"BURUNDI"},
    {name:"CAMBODIA"},
    {name:"CAMEROON"},
    {name:"CAPE VERDE ISLANDS"},
    {name:"CHAD"},
    {name:"CHILE"},
    {name:"CONGO"},
    {name:"COSTA RICA"},
    {name:"CROATIA"},
    {name:"CYPRUS"},
    {name:"CZECH REPUBLIC"},
    {name:"DENMARK"},
    {name:"DJIBOUTI"},
    {name:"DOMINICA"},
    {name:"EGYPT"},
    {name:"ERITREA"},
    {name:"ESTONIA"},
    {name:"ETHIOPIA"},
    {name:"FIJI"},
    {name:"FINLAND"},
    {name:"FRENCH POLYNESIA"},
    {name:"GABON"},
    {name:"GAMBIA"},
    {name:"GEORGIA"},
    {name:"GHANA"},
    {name:"GREECE"},
    {name:"GRENADA"},
    {name:"GUINEA"},
    {name:"GUYANA"},
    {name:"HUNGARY"},
    {name:"ICELAND"},
    {name:"INDONESIA"},
    {name:"IRAN"},
    {name:"IRAQ"},
    {name:"JAMAICA"},
    {name:"JORDAN"},
    {name:"KAZAKHSTAN"},
    {name:"KENYA"},
    {name:"KOREA"},
    {name:"KUWAIT"},
    {name:"LATVIA"},
    {name:"LEBANON"},
    {name:"LIBERIA"},
    {name:"LIBYA"},
    {name:"LITHUANIA"},
    {name:"LUXEMBOURG"},
    {name:"MADAGASCAR"},
    {name:"MALAWI"},
    {name:"MALAYSIA"},
    {name:"MALDIVES"},
    {name:"MALI"},
    {name:"MALTA"},
    {name:"MAURITANIA"},
    {name:"MAURITIUS"},
    {name:"MONACO"},
    {name:"MONGOLIA"},
    {name:"MONTENEGRO"},
    {name:"MOROCCO"},
    {name:"MOZAMBIQUE"},
    {name:"NAMIBIA"},
    {name:"NEPAL"},
    {name:"NEW ZEALAND"},
    {name:"NICARAGUA"},
    {name:"NIGER"},
    {name:"NIGERIA"},
    {name:"NORWAY"},
    {name:"OMAN"},
    {name:"PAKISTAN"},
    {name:"PANAMA"},
    {name:"PAPUA NEW GUINEA"},
    {name:"PARAGUAY"},
    {name:"PERU"},
    {name:"POLAND"},
    {name:"PORTUGAL"},
    {name:"QATAR"},
    {name:"ROMANIA"},
    {name:"RWANDA"},
    {name:"SAUDI ARABIA"},
    {name:"SENEGAL"},
    {name:"SERBIA"},
    {name:"SIERRA LEONE"},
    {name:"SINGAPORE"},
    {name:"SLOVAKIA"},
    {name:"SLOVENIA"},
    {name:"SOLOMON ISLANDS"},
    {name:"SOMALIA"},
    {name:"SRI LANKA"},
    {name:"SUDAN"},
    {name:"SURINAME"},
    {name:"SWAZILAND"},
    {name:"TAJIKISTAN"},
    {name:"THAILAND"},
    {name:"TOGO"},
    {name:"TRINIDAD AND TOBAGO"},
    {name:"TUNISIA"},
    {name:"TURKEY"},
    {name:"TURKMENISTAN"},
    {name:"TUVALU"},
    {name:"UGANDA"},
    {name:"UKRAINE"},
    {name:"UNITED ARAB EMIRATES"},
    {name:"UNITED STATES"},
    {name:"URUGUAY"},
    {name:"UZBEKISTAN"},
    {name:"VANUATU"},
    {name:"YEMEN"},
    {name:"ZAMBIA"},

  ];
  

const Countries = (props) => {
  const [countryData, setCountryData] = useState([]);

  const getCountryData = async () => {    
    setCountryData(
      mockedData.filter(function(mockedData) {
        return mockedData;
      })
    );
  };

  useEffect(() => {
    console.log("Data ", { mockedData });
    getCountryData();
  }, []);

  return (
    <CountriesDropdown
      
      dropdownData={countryData}
      
    />
    
  );
};

export default Countries;