import { db } from '../database/firebase'
import { collection, addDoc, Timestamp, query, orderBy, onSnapshot, where, serverTimestamp } from 'firebase/firestore'

const getFormDefaults = (clientID) => {
    let formData = {}

    if (clientID === "") {
        let commentFields = [
            "commentQ1", "commentQ2", "commentQ3", "commentQ4", "commentQ5", "commentQ6", "commentQ7", "commentQ8", "commentQ9", "commentQ10",
            "commentQ11", "commentQ12", "commentQ13", "commentQ14", "commentQ15", "commentQ16", "commentQ17", "commentQ17a", "commentQ17b",
            "commentQ17c", "commentQ17d", "commentQ18", "commentQ19", "commentQ20", "commentQ21", "commentQ22", "commentQ23", "commentQ24",
            "commentQ25", "commentQ26", "commentQ27", "commentQ28", "commentQ29", "commentQ30", "commentQ31", "commentQ32", "commentQ33",
            "commentQ34", "commentQ35", "commentQ36", "commentQ37", "commentQ38", "commentQ39", "commentQ40", "commentQ41", "commentQ42",
            "commentQ43", "commentQ44", "commentQ45", "commentQ46", "commentQ47", "commentQ48", "commentQ49", "commentQ50", "commentQ51",
            "commentQ52", "commentQ53", "commentQ54", "commentQ55", "commentQ56", "commentQ57", "commentQ58", "commentQ59", "commentQ60",
            "commentQ61", "commentQ62", "commentQ63", "commentQ64", "commentQ65", "commentQ66", "commentQ67", "commentQ68", "commentQ69",
            "commentQ70", "commentQ71", "commentQ72", "commentQ73", "commentDateOfBirth", "commentCountry", "commentGender",
            "commentResidence", "commentHousingSituation", "commentEducation", "commentRecentConflict", "commentLanguage", "commentDemographics"
        ];
        let fields = [
            "Q1", "Q2", "Q3", "Q4", "Q5", "Q6", "Q7", "Q8", "Q9", "Q10", "Q11", "Q12", "Q13", "Q14", "Q15", "Q16", "Q17", "Q17a", "Q17b", "Q17c",
            "Q17d", "Q18", "Q19", "Q20", "Q21", "Q22", "Q23", "Q24", "Q25", "Q26", "Q27", "Q28", "Q29", "Q30", "Q31", "Q32", "Q33", "Q34", "Q35",
            "Q36", "Q37", "Q38", "Q39", "Q40", "Q41", "Q42", "Q43", "Q44", "Q45", "Q46", "Q47", "Q48", "Q49", "Q50", "Q51", "Q52", "Q53", "Q54",
            "Q55", "Q56", "Q57", "Q58", "Q59", "Q60", "Q61", "Q62", "Q63", "Q64", "Q65", "Q66", "Q67", "Q68", "Q69", "Q70", "Q71", "Q72", "Q73",
            "Q30a", "Q31a", "Q32a", "Q33a", "Q34a", "Q35a", "Q36a", "Q37a", "Q38a", "Q39a", "Q40a", "Q41a", "Q42a", "Q43a", "Q44a", "Q45a", "Q46a",
            "Q47a", "Q48a", "Q49a", "Q50a", "Q51a", "Q52a", "Q53a", "Q54a"
        ]

        for (let i = 0; i < commentFields.length; ++i)
            formData[commentFields[i]] = "";

        for (let i = 0; i < fields.length; ++i)
            if (i < 4)
                formData[fields[i]] = 0;
            else if (i < 21)
                formData[fields[i]] = "";
            else if (i < 26)
                formData[fields[i]] = "Does Not Describe Me";
            else if (i < 33)
                formData[fields[i]] = "None";
            else if (i < 58)
                formData[fields[i]] = "";
            else if (i == 58)
                formData[fields[i]] = "Does Not Describe Me";
            else if (i < 77)
                formData[fields[i]] = 0;
            else
                formData[fields[i]] = "";

        formData["DateOfBirth"] = "";
    }
    else {
        const q = query(collection(db, 'Responses'), where('ClientID', "==", clientID))
        onSnapshot(q, (querySnapshot) => {
            formData = (querySnapshot.docs.map(doc => ({
                DateOfBirth: doc.data().DateOfBirth,
                ClientName: doc.data().ClientName,
                ClientID: doc.data().ClientID,
                DateOfInterview: doc.data().DateOfInterview,
                Education: doc.data().Education,
                Gender: doc.data().Gender(),
                HousingSituation: doc.data().HousingSituation,
                Interviewer: doc.data().Interviewer,
                Langauge: doc.data().Langauge,
                PlaceOfInterview: doc.data().PlaceOfInterview,
                RecentConflict: doc.data().RecentConflict,
                Country: doc.data().Country,
                Residence: doc.data().Residence,
                commentQ1: doc.data().commentQ1,
                commentQ2: doc.data().commentQ2,
                commentQ3: doc.data().commentQ3,
                commentQ4: doc.data().commentQ4,
                commentQ5: doc.data().commentQ5,
                commentQ6: doc.data().commentQ6,
                commentQ7: doc.data().commentQ7,
                commentQ8: doc.data().commentQ8,
                commentQ9: doc.data().commentQ9,
                commentQ10: doc.data().commentQ10,
                commentQ11: doc.data().commentQ11,
                commentQ12: doc.data().commentQ12,
                commentQ13: doc.data().commentQ13,
                commentQ14: doc.data().commentQ14,
                commentQ15: doc.data().commentQ15,
                commentQ16: doc.data().commentQ16,
                commentQ17: doc.data().commentQ17,
                commentQ17a: doc.data().commentQ17a,
                commentQ17b: doc.data().commentQ17b,
                commentQ17c: doc.data().commentQ17c,
                commentQ17d: doc.data().commentQ17d,
                commentQ18: doc.data().commentQ18,
                commentQ19: doc.data().commentQ19,
                commentQ20: doc.data().commentQ20,
                commentQ21: doc.data().commentQ21,
                commentQ22: doc.data().commentQ22,
                commentQ23: doc.data().commentQ23,
                commentQ24: doc.data().commentQ24,
                commentQ25: doc.data().commentQ25,
                commentQ26: doc.data().commentQ26,
                commentQ27: doc.data().commentQ27,
                commentQ28: doc.data().commentQ28,
                commentQ29: doc.data().commentQ29,
                commentQ30: doc.data().commentQ30,
                commentQ31: doc.data().commentQ31,
                commentQ32: doc.data().commentQ32,
                commentQ33: doc.data().commentQ33,
                commentQ34: doc.data().commentQ34,
                commentQ35: doc.data().commentQ35,
                commentQ36: doc.data().commentQ36,
                commentQ37: doc.data().commentQ37,
                commentQ38: doc.data().commentQ38,
                commentQ39: doc.data().commentQ39,
                commentQ40: doc.data().commentQ40,
                commentQ41: doc.data().commentQ41,
                commentQ42: doc.data().commentQ42,
                commentQ43: doc.data().commentQ43,
                commentQ44: doc.data().commentQ44,
                commentQ45: doc.data().commentQ45,
                commentQ46: doc.data().commentQ46,
                commentQ47: doc.data().commentQ47,
                commentQ48: doc.data().commentQ48,
                commentQ49: doc.data().commentQ49,
                commentQ50: doc.data().commentQ50,
                commentQ51: doc.data().commentQ51,
                commentQ52: doc.data().commentQ52,
                commentQ53: doc.data().commentQ53,
                commentQ54: doc.data().commentQ54,
                commentQ55: doc.data().commentQ55,
                commentQ56: doc.data().commentQ56,
                commentQ57: doc.data().commentQ57,
                commentQ58: doc.data().commentQ58,
                commentQ59: doc.data().commentQ59,
                commentQ60: doc.data().commentQ60,
                commentQ61: doc.data().commentQ61,
                commentQ62: doc.data().commentQ62,
                commentQ63: doc.data().commentQ63,
                commentQ64: doc.data().commentQ64,
                commentQ65: doc.data().commentQ65,
                commentQ66: doc.data().commentQ66,
                commentQ67: doc.data().commentQ67,
                commentQ68: doc.data().commentQ68,
                commentQ69: doc.data().commentQ69,
                commentQ70: doc.data().commentQ70,
                commentQ71: doc.data().commentQ71,
                commentQ72: doc.data().commentQ72,
                commentQ73: doc.data().commentQ73,
                commentDateOfBirth: doc.data().commentDateOfBirth,
                commentCountry: doc.data().commentCountry,
                commentGender: doc.data().commentGender,
                commentResidence: doc.data().commentResidence,
                commentHousingSituation: doc.data().commentHousingSituation,
                commentEducation: doc.data().commentEducation,
                commentRecentConflict: doc.data().commentRecentConflict,
                commentLanguage: doc.data().commentLanguage,
                commentDemographics: doc.data().commentDemographics,
                Q1: doc.data().Q1,
                Q2: doc.data().Q2,
                Q3: doc.data().Q3,
                Q4: doc.data().Q4,
                Q5: doc.data().Q5,
                Q6: doc.data().Q6,
                Q7: doc.data().Q7,
                Q8: doc.data().Q8,
                Q9: doc.data().Q9,
                Q10: doc.data().Q10,
                Q11: doc.data().Q11,
                Q12: doc.data().Q12,
                Q13: doc.data().Q13,
                Q14: doc.data().Q14,
                Q15: doc.data().Q15,
                Q16: doc.data().Q16,
                Q17: doc.data().Q17,
                Q17a: doc.data().Q17a,
                Q17b: doc.data().Q17b,
                Q17c: doc.data().Q17c,
                Q17d: doc.data().Q17d,
                Q18: doc.data().Q18,
                Q19: doc.data().Q19,
                Q20: doc.data().Q20,
                Q21: doc.data().Q21,
                Q22: doc.data().Q22,
                Q23: doc.data().Q23,
                Q24: doc.data().Q24,
                Q25: doc.data().Q25,
                Q26: doc.data().Q26,
                Q27: doc.data().Q27,
                Q28: doc.data().Q28,
                Q29: doc.data().Q29,
                Q30: doc.data().Q30,
                Q31: doc.data().Q31,
                Q32: doc.data().Q32,
                Q33: doc.data().Q33,
                Q34: doc.data().Q34,
                Q35: doc.data().Q35,
                Q36: doc.data().Q36,
                Q37: doc.data().Q37,
                Q38: doc.data().Q38,
                Q39: doc.data().Q39,
                Q40: doc.data().Q40,
                Q41: doc.data().Q41,
                Q42: doc.data().Q42,
                Q43: doc.data().Q43,
                Q44: doc.data().Q44,
                Q45: doc.data().Q45,
                Q46: doc.data().Q46,
                Q47: doc.data().Q47,
                Q48: doc.data().Q48,
                Q49: doc.data().Q49,
                Q50: doc.data().Q50,
                Q51: doc.data().Q51,
                Q52: doc.data().Q52,
                Q53: doc.data().Q53,
                Q54: doc.data().Q54,
                Q55: doc.data().Q55,
                Q56: doc.data().Q56,
                Q57: doc.data().Q57,
                Q58: doc.data().Q58,
                Q59: doc.data().Q59,
                Q60: doc.data().Q60,
                Q61: doc.data().Q61,
                Q62: doc.data().Q62,
                Q63: doc.data().Q63,
                Q64: doc.data().Q64,
                Q65: doc.data().Q65,
                Q66: doc.data().Q66,
                Q67: doc.data().Q67,
                Q68: doc.data().Q68,
                Q69: doc.data().Q69,
                Q70: doc.data().Q70,
                Q71: doc.data().Q71,
                Q72: doc.data().Q72,
                Q73: doc.data().Q73,
            })))

        })
    }

    return formData;
}

const writeToDatabase = async (e, formData) => {
    e.preventDefault()

    try {
        await addDoc(collection(db, 'Responses'), {
            // Question Responses
            ClientName: formData["ClientName"],
            ClientID: formData["ClientID"],
            PlaceOfInterview: formData["PlaceOfInterview"],
            Interviewer: formData["email"],
            DateOfInterview: serverTimestamp(),

            Gender: formData["Gender"],
            DateOfBirth: formData["DateOfBirth"],
            Country: formData["Country"],
            Residence: formData["Residence"],
            HousingSituation: formData["HousingSituation"],
            Education: formData["Education"],
            RecentConflict: formData["RecentConflict"],
            Langauge: formData["Langauge"],

            Q1: formData["Q1"],
            Q2: formData["Q2"],
            Q3: formData["Q3"],
            Q4: formData["Q4"],
            Q5: formData["Q5"],
            Q6: formData["Q6"],
            Q7: formData["Q7"],
            Q8: formData["Q8"],
            Q9: formData["Q9"],
            Q10: formData["Q10"],
            Q11: formData["Q11"],
            Q12: formData["Q12"],
            Q13: formData["Q13"],
            Q14: formData["Q14"],
            Q15: formData["Q15"],
            Q16: formData["Q16"],
            Q17: formData["Q17"],
            Q17: formData["Q17a"],
            Q17: formData["Q17b"],
            Q17: formData["Q17c"],
            Q17: formData["Q17d"],
            Q18: formData["Q18"],
            Q19: formData["Q19"],
            Q20: formData["Q20"],
            Q21: formData["Q21"],
            Q22: formData["Q22"],
            Q23: formData["Q23"],
            Q24: formData["Q24"],
            Q25: formData["Q25"],
            Q26: formData["Q26"],
            Q27: formData["Q27"],
            Q28: formData["Q28"],
            Q29: formData["Q29"],
            Q30: formData["Q30"],
            Q31: formData["Q31"],
            Q32: formData["Q32"],
            Q33: formData["Q33"],
            Q34: formData["Q34"],
            Q35: formData["Q35"],
            Q36: formData["Q36"],
            Q37: formData["Q37"],
            Q38: formData["Q38"],
            Q39: formData["Q39"],
            Q40: formData["Q40"],
            Q41: formData["Q41"],
            Q42: formData["Q42"],
            Q43: formData["Q43"],
            Q44: formData["Q44"],
            Q45: formData["Q45"],
            Q46: formData["Q46"],
            Q47: formData["Q47"],
            Q48: formData["Q48"],
            Q49: formData["Q49"],
            Q50: formData["Q50"],
            Q51: formData["Q51"],
            Q52: formData["Q52"],
            Q53: formData["Q53"],
            Q54: formData["Q54"],
            Q55: formData["Q55"],
            Q56: formData["Q56"],
            Q57: formData["Q57"],
            Q58: formData["Q58"],
            Q59: formData["Q59"],
            Q60: formData["Q60"],
            Q61: formData["Q61"],
            Q62: formData["Q62"],
            Q63: formData["Q63"],
            Q64: formData["Q64"],
            Q65: formData["Q65"],
            Q66: formData["Q66"],
            Q67: formData["Q67"],
            Q68: formData["Q68"],
            Q69: formData["Q69"],
            Q70: formData["Q70"],
            Q71: formData["Q71"],
            Q72: formData["Q72"],
            Q73: formData["Q73"],

            // Comments
            commentDemographics: formData["commentDemographics"],

            commentGender: formData["commentGender"],
            commentDateOfBirth: formData["commentDateOfBirth"],
            commentCountry: formData["commentCountry"],
            commentResidence: formData["commentResidence"],
            commentHousingSituation: formData["commentHousingSituation"],
            commentEducation: formData["commentEducation"],
            commentRecentConflict: formData["commentRecentConflict"],
            commentLanguage: formData["commentLanguage"],

            commentQ1: formData["commentQ1"],
            commentQ2: formData["commentQ2"],
            commentQ3: formData["commentQ3"],
            commentQ4: formData["commentQ4"],
            commentQ5: formData["commentQ5"],
            commentQ6: formData["commentQ6"],
            commentQ7: formData["commentQ7"],
            commentQ8: formData["commentQ8"],
            commentQ9: formData["commentQ9"],
            commentQ10: formData["commentQ10"],
            commentQ11: formData["commentQ11"],
            commentQ12: formData["commentQ12"],
            commentQ13: formData["commentQ13"],
            commentQ14: formData["commentQ14"],
            commentQ15: formData["commentQ15"],
            commentQ16: formData["commentQ16"],
            commentQ17: formData["commentQ17"],
            commentQ17: formData["commentQ17a"],
            commentQ17: formData["commentQ17b"],
            commentQ17: formData["commentQ17c"],
            commentQ17: formData["commentQ17d"],
            commentQ18: formData["commentQ18"],
            commentQ19: formData["commentQ19"],
            commentQ20: formData["commentQ20"],
            commentQ21: formData["commentQ21"],
            commentQ22: formData["commentQ22"],
            commentQ23: formData["commentQ23"],
            commentQ24: formData["commentQ24"],
            commentQ25: formData["commentQ25"],
            commentQ26: formData["commentQ26"],
            commentQ27: formData["commentQ27"],
            commentQ28: formData["commentQ28"],
            commentQ29: formData["commentQ29"],
            commentQ30: formData["commentQ30"],
            commentQ31: formData["commentQ31"],
            commentQ32: formData["commentQ32"],
            commentQ33: formData["commentQ33"],
            commentQ34: formData["commentQ34"],
            commentQ35: formData["commentQ35"],
            commentQ36: formData["commentQ36"],
            commentQ37: formData["commentQ37"],
            commentQ38: formData["commentQ38"],
            commentQ39: formData["commentQ39"],
            commentQ40: formData["commentQ40"],
            commentQ41: formData["commentQ41"],
            commentQ42: formData["commentQ42"],
            commentQ43: formData["commentQ43"],
            commentQ44: formData["commentQ44"],
            commentQ45: formData["commentQ45"],
            commentQ46: formData["commentQ46"],
            commentQ47: formData["commentQ47"],
            commentQ48: formData["commentQ48"],
            commentQ49: formData["commentQ49"],
            commentQ50: formData["commentQ50"],
            commentQ51: formData["commentQ51"],
            commentQ52: formData["commentQ52"],
            commentQ53: formData["commentQ53"],
            commentQ54: formData["commentQ54"],
            commentQ55: formData["commentQ55"],
            commentQ56: formData["commentQ56"],
            commentQ57: formData["commentQ57"],
            commentQ58: formData["commentQ58"],
            commentQ59: formData["commentQ59"],
            commentQ60: formData["commentQ60"],
            commentQ61: formData["commentQ61"],
            commentQ62: formData["commentQ62"],
            commentQ63: formData["commentQ63"],
            commentQ64: formData["commentQ64"],
            commentQ65: formData["commentQ65"],
            commentQ66: formData["commentQ66"],
            commentQ67: formData["commentQ67"],
            commentQ68: formData["commentQ68"],
            commentQ69: formData["commentQ69"],
            commentQ70: formData["commentQ70"],
            commentQ71: formData["commentQ71"],
            commentQ72: formData["commentQ72"],
            commentQ73: formData["commentQ73"],
        })

    } catch (err) {
        alert(err)
    }
}

export { writeToDatabase };
export { getFormDefaults };